// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Team {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    fio?: string;
    info?: string;
    image?: { data: Media };
  };
}
export interface Team_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  fio?: string;
  info?: string;
  image?: Media_Plain;
}

export interface Team_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  fio?: string;
  info?: string;
  image?: number;
}

export interface Team_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  fio?: string;
  info?: string;
  image?: AdminPanelRelationPropertyModification<Media_Plain>;
}
