// Interface automatically generated by schemas-to-ts

export interface ProjectsTag {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    text?: string;
  };
}
export interface ProjectsTag_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  text?: string;
}

export interface ProjectsTag_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  text?: string;
}

export interface ProjectsTag_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  text?: string;
}
