// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Service {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    shortText?: string;
    icon?: { data: Media };
    content?: string;
    image?: { data: Media };
  };
}
export interface Service_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  shortText?: string;
  icon?: Media_Plain;
  content?: string;
  image?: Media_Plain;
}

export interface Service_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  shortText?: string;
  icon?: number;
  content?: string;
  image?: number;
}

export interface Service_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  shortText?: string;
  icon?: AdminPanelRelationPropertyModification<Media_Plain>;
  content?: string;
  image?: AdminPanelRelationPropertyModification<Media_Plain>;
}
