// Interface automatically generated by schemas-to-ts

import { Services } from '../../../../components/sections/interfaces/Services';
import { Advantage } from '../../../advantage/content-types/advantage/advantage';
import { Services_Plain } from '../../../../components/sections/interfaces/Services';
import { Advantage_Plain } from '../../../advantage/content-types/advantage/advantage';
import { Services_NoRelations } from '../../../../components/sections/interfaces/Services';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface SectionAdvantage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    section?: Services;
    advantages_items: { data: Advantage[] };
  };
}
export interface SectionAdvantage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  section?: Services_Plain;
  advantages_items: Advantage_Plain[];
}

export interface SectionAdvantage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  section?: Services_NoRelations;
  advantages_items: number[];
}

export interface SectionAdvantage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  section?: Services_Plain;
  advantages_items: AdminPanelRelationPropertyModification<Advantage_Plain>;
}
