// Interface automatically generated by schemas-to-ts

import { Services } from '../../../../components/sections/interfaces/Services';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { About } from '../../../about/content-types/about/about';
import { Services_Plain } from '../../../../components/sections/interfaces/Services';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { About_Plain } from '../../../about/content-types/about/about';
import { Services_NoRelations } from '../../../../components/sections/interfaces/Services';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface SectionAbout {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    section?: Services;
    image?: { data: Media };
    about_items: { data: About[] };
  };
}
export interface SectionAbout_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  section?: Services_Plain;
  image?: Media_Plain;
  about_items: About_Plain[];
}

export interface SectionAbout_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  section?: Services_NoRelations;
  image?: number;
  about_items: number[];
}

export interface SectionAbout_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  section?: Services_Plain;
  image?: AdminPanelRelationPropertyModification<Media_Plain>;
  about_items: AdminPanelRelationPropertyModification<About_Plain>;
}
