// Interface automatically generated by schemas-to-ts

import { Services } from '../../../../components/sections/interfaces/Services';
import { Services_Plain } from '../../../../components/sections/interfaces/Services';
import { Services_NoRelations } from '../../../../components/sections/interfaces/Services';

export interface SectionService {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    section?: Services;
  };
}
export interface SectionService_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  section?: Services_Plain;
}

export interface SectionService_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  section?: Services_NoRelations;
}

export interface SectionService_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  section?: Services_Plain;
}
