// Interface automatically generated by schemas-to-ts

export interface Header {
  title?: string;
  description?: string;
}
export interface Header_Plain {
  title?: string;
  description?: string;
}

export interface Header_NoRelations {
  title?: string;
  description?: string;
}

