// Interface automatically generated by schemas-to-ts

export interface SectionHeader {
  title?: string;
  description?: string;
}
export interface SectionHeader_Plain {
  title?: string;
  description?: string;
}

export interface SectionHeader_NoRelations {
  title?: string;
  description?: string;
}

