// Interface automatically generated by schemas-to-ts

export interface About {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    text?: string;
    num?: string;
  };
}
export interface About_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  text?: string;
  num?: string;
}

export interface About_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  text?: string;
  num?: string;
}

export interface About_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  text?: string;
  num?: string;
}
