// Interface automatically generated by schemas-to-ts

import { Services } from '../../../../components/sections/interfaces/Services';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Services_Plain } from '../../../../components/sections/interfaces/Services';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Services_NoRelations } from '../../../../components/sections/interfaces/Services';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface SectionClient {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    section?: Services;
    clients?: { data: Media[] };
  };
}
export interface SectionClient_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  section?: Services_Plain;
  clients?: Media_Plain[];
}

export interface SectionClient_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  section?: Services_NoRelations;
  clients?: number[];
}

export interface SectionClient_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  section?: Services_Plain;
  clients?: AdminPanelRelationPropertyModification<Media_Plain>[];
}
