// Interface automatically generated by schemas-to-ts

import { Services } from '../../../../components/sections/interfaces/Services';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Services_Plain } from '../../../../components/sections/interfaces/Services';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Services_NoRelations } from '../../../../components/sections/interfaces/Services';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface SectionHero {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    section?: Services;
    poster?: { data: Media };
    video?: { data: Media };
  };
}
export interface SectionHero_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  section?: Services_Plain;
  poster?: Media_Plain;
  video?: Media_Plain;
}

export interface SectionHero_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  section?: Services_NoRelations;
  poster?: number;
  video?: number;
}

export interface SectionHero_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  section?: Services_Plain;
  poster?: AdminPanelRelationPropertyModification<Media_Plain>;
  video?: AdminPanelRelationPropertyModification<Media_Plain>;
}
