// Interface automatically generated by schemas-to-ts

import { Header } from '../../section/interfaces/Header';
import { Button } from '../../ui/interfaces/Button';
import { Header_Plain } from '../../section/interfaces/Header';
import { Button_Plain } from '../../ui/interfaces/Button';
import { Header_NoRelations } from '../../section/interfaces/Header';
import { Button_NoRelations } from '../../ui/interfaces/Button';

export interface Services {
  header?: Header;
  button?: Button;
}
export interface Services_Plain {
  header?: Header_Plain;
  button?: Button_Plain;
}

export interface Services_NoRelations {
  header?: Header_NoRelations;
  button?: Button_NoRelations;
}

