// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { ProjectsTag } from '../../../projects-tag/content-types/projects-tag/projects-tag';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { ProjectsTag_Plain } from '../../../projects-tag/content-types/projects-tag/projects-tag';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Project {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    text?: string;
    image?: { data: Media };
    projects_tags: { data: ProjectsTag[] };
    slug?: string;
    about?: string;
    what_done?: string;
    result?: string;
  };
}
export interface Project_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  text?: string;
  image?: Media_Plain;
  projects_tags: ProjectsTag_Plain[];
  slug?: string;
  about?: string;
  what_done?: string;
  result?: string;
}

export interface Project_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  text?: string;
  image?: number;
  projects_tags: number[];
  slug?: string;
  about?: string;
  what_done?: string;
  result?: string;
}

export interface Project_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  text?: string;
  image?: AdminPanelRelationPropertyModification<Media_Plain>;
  projects_tags: AdminPanelRelationPropertyModification<ProjectsTag_Plain>;
  slug?: string;
  about?: string;
  what_done?: string;
  result?: string;
}
